import type { LocalSession } from "./schema.js";
import type { OpenSasaStore } from "./storage.js";

export const demoSeedSessionInputs = [
  {
    timestamp: "2026-06-09T12:00:00.000Z",
    provider: "OpenAI",
    model_id: "gpt-5",
    tool: "Codex",
    task_type: "bug_fix",
    final_outcome: "accepted",
    work_mode: "manual_log",
    language: "TypeScript",
    framework: "Node.js",
    duration_seconds: 420,
    retry_count: 1,
    error_count: 0,
    input_tokens_estimate: 1200,
    output_tokens_estimate: 500,
    cached_tokens_estimate: 100,
    estimated_cost_usd: 0.5,
    cost_source: "estimated",
    repo_size_bucket: "small",
    file_count_bucket: "medium",
    changed_file_count_bucket: "tiny",
    lines_added_bucket: "small",
    lines_removed_bucket: "tiny",
    tests_outcome: "passed",
    build_outcome: "passed",
    lint_outcome: "not_run",
    typecheck_outcome: "passed",
  },
  {
    timestamp: "2026-06-10T12:00:00.000Z",
    provider: "Anthropic",
    model_id: "claude-sonnet-4.5",
    tool: "Claude Code",
    task_type: "feature",
    final_outcome: "partially_accepted",
    work_mode: "manual_log",
    language: "Python",
    framework: "Django",
    duration_seconds: 1500,
    retry_count: 2,
    error_count: 1,
    input_tokens_estimate: 2400,
    output_tokens_estimate: 900,
    estimated_cost_usd: 1.2,
    cost_source: "estimated",
    repo_size_bucket: "medium",
    file_count_bucket: "large",
    changed_file_count_bucket: "small",
    lines_added_bucket: "medium",
    lines_removed_bucket: "small",
    tests_outcome: "passed",
    build_outcome: "passed",
    lint_outcome: "passed",
    typecheck_outcome: "not_run",
  },
  {
    timestamp: "2026-06-11T12:00:00.000Z",
    provider: "Google",
    model_id: "gemini-cli",
    tool: "Gemini CLI",
    task_type: "documentation",
    final_outcome: "rejected",
    work_mode: "manual_log",
    language: "Markdown",
    duration_seconds: 180,
    retry_count: 3,
    error_count: 2,
    input_tokens_estimate: 900,
    output_tokens_estimate: 300,
    estimated_cost_usd: 0.15,
    cost_source: "estimated",
    repo_size_bucket: "small",
    file_count_bucket: "medium",
    changed_file_count_bucket: "tiny",
    lines_added_bucket: "small",
    lines_removed_bucket: "tiny",
    tests_outcome: "not_run",
    build_outcome: "not_run",
    lint_outcome: "not_run",
    typecheck_outcome: "not_run",
    manual_review_outcome: "rejected",
  },
] as const;

export function createDemoSeedSessions(store: OpenSasaStore): LocalSession[] {
  return demoSeedSessionInputs.map((session) => store.createSession(session));
}
